repos:
  - repo: local
    hooks:
      - id: csharpier
        name: Run CSharpier on C# files
        entry: csharpier format .
        language: system
        files: '\\.cs$'
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit