repos:
  - repo: local
    hooks:
      - id: dotnet-tool-restore
        name: Install .NET tools
        entry: dotnet tool restore
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - pre-commit
          - pre-push
          - post-checkout
          - post-rewrite
      - id: csharpier
        name: Run CSharpier on C# files
        entry: csharpier format .
        language: system
        files: '\\.cs$'
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit